version: '3'

services:
  # Web server to serve the example
  web:
    image: nginx:alpine
    ports:
      - "7327:80"
    volumes:
      - ./example:/usr/share/nginx/html
      - ./components:/usr/share/nginx/html/components
      - ./styles:/usr/share/nginx/html/styles
      - ./dist:/usr/share/nginx/html/dist
    depends_on:
      - builder
      - websocket
    restart: unless-stopped
    # Use bash for the entrypoint shell
    entrypoint: ["/bin/sh", "-c", "nginx -g 'daemon off;'"]
    # Add healthcheck
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  # WebSocket server for hot-reload
  websocket:
    image: node:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./components:/app/components
      - ./dist:/app/dist
      - ./example:/app/example
      - ./server:/app/server
      - ./styles:/app/styles
      - ./files:/app/files
      - websocket_node_modules:/app/node_modules
    working_dir: /app
    command: >
      sh -c "
        echo 'Setting up WebSocket server...' &&
        cd /app/server &&
        npm install ws --no-save &&
        node /app/server/websocket-server.js
      "
    restart: unless-stopped

  # Builder service to watch for changes and rebuild
  builder:
    image: node:alpine
    volumes:
      - ./components:/app/components
      - ./dist:/app/dist
      - ./example:/app/example
      - ./server:/app/server
      - ./styles:/app/styles
      - ./files:/app/files
      - builder_node_modules:/app/node_modules
    working_dir: /app
    depends_on:
      - websocket
    command: >
      sh -c "
        echo 'Setting up build environment...' &&
        apk add --no-cache inotify-tools &&
        mkdir -p /app/dist &&
        mkdir -p /app/example/dist &&
        mkdir -p /app/example/build-status &&

        # Wait for WebSocket server to start
        echo 'Waiting for WebSocket server...' &&
        until wget -q --spider http://websocket:8080 2>/dev/null || nc -z websocket 8080; do
          echo 'WebSocket server not ready yet...'
          sleep 1
        done &&
        echo 'WebSocket server is ready!' &&

        # Initial build
        echo 'Performing initial build...' &&
        cd /app/server &&
        npm install --no-save &&
        node /app/server/build.js | node /app/server/websocket-client.js &&
        cp /app/dist/* /app/example/dist/ &&

        # Watch for changes
        echo 'Watching for changes...' &&
        while true; do
          inotifywait -r -e modify,create,delete /app/components &&
          echo 'Changes detected, rebuilding...' &&

          # Update version
          echo \$(date +%s) > /app/components/version.txt &&

          # Attempt to build and pipe output to WebSocket server
          node /app/server/build.js | node /app/server/websocket-client.js &&

          # Copy build files
          cp /app/dist/* /app/example/dist/
        done
      "

volumes:
  websocket_node_modules:
  builder_node_modules: