services:
  # Combined j e l l i c u l e service
  jellicule:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7327:7327"  # HTTP server
      - "8080:8080"  # WebSocket server
    volumes:
      - components_volume:/app/components
      - dist_volume:/app/dist
      - styles_volume:/app/styles
      - ./pwa-service:/app/pwa-service
      - ./service:/app/service
      - ./meta:/app/meta
      - ./files:/app/files:ro
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:7327/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    command: >
      sh -c "
        # Copy files from files directory to components and styles if they don't exist
        if [ ! -d \"/app/components/layout\" ]; then
          echo 'Initializing components directory...' &&
          cp -r /app/files/components/* /app/components/ || true
        fi &&

        if [ ! -f \"/app/styles/jellicule.css\" ]; then
          echo 'Initializing styles directory...' &&
          cp -r /app/files/styles/* /app/styles/ || true
        fi &&

        # Start the server
        bun run /app/service/server.js
      "

volumes:
  components_volume:
  styles_volume:
  dist_volume: