version: '3'

services:
  web:
    image: nginx:alpine
    ports:
      - "7327:80"
    volumes:
      - ./example:/usr/share/nginx/html
      - ./dist:/usr/share/nginx/html/dist
      - ./styles:/usr/share/nginx/html/styles
    restart: unless-stopped
    # Use bash for the entrypoint shell
    entrypoint: ["/bin/sh", "-c", "nginx -g 'daemon off;'"]
    # Add healthcheck
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
